### PR TITLE
12 Authorization Concept

### PR DESCRIPTION
**Pull request by myluki2000**
This PR includes the wiki pages describing our Authorization Concept as discussed by me, @PaulBredl and @BlueWaves2

### CODE REVIEW

**Comment by PaulBredl** [comment]
Stupid question I just had. Why doesn't the media/content whatever just stores which course it belongs to?
That would mean the media service only has to ask the keycloak. I think we reasons for not making it this may, but I don't remember them.

As far as I know, we don't allow that content is moved to another course, and even that would not be too complicated.

**Comment by myluki2000** [comment]
> Why doesn't the media/content whatever just stores which course it belongs to?

We said that we want to prevent data duplication if possible, thus we don't want to store the relationship both on the course and on the media end. Also, because it wouldn't even be a direct relationship, because there also sits "Chapter" and "MediaContent" between Course and Media

**Comment by PaulBredl** [comment]
But the duplication is not a problem because we don't allow moving content from one service to another and even if we did it would still be less complicated than having this unnecessary call chain from a content service.

**Comment by myluki2000** [comment]
Remember that we're talking about the media records here, stored on the MediaService, not MediaContent! And media records totally can be linked by multiple courses and linkings might be changed. Media records are not course-specific, they're just files linked to by some course's chapter's contents

**Comment by PaulBredl** [comment]
@myluki2000 I'm gonna be honest, I personally dislike this approach but you guys put the brain into it and I understand your reasoning.

**Comment by myluki2000** [comment]
I mean we could also ask customer Niklas if he is happy with this design or if he rather wants something else. Shouldn't take too long, we could do it this evening.

**Review by PaulBredl — APPROVED** [review]
Looks fine for now

**Comment by Keyshal-211** [comment]
Fine for me with your Conversation.

**Review by Keyshal-211 — COMMENTED** [review]
lgd

**Pull request merged**
